development:
  adapter: postgresql
  database: amazon_development
  host: localhost
  username: root
  password: 
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: amazon_test
  host: localhost
  username: root
  password: 
  pool: 5
  timeout: 5000
